repos:

  - repo: local
    hooks:
      - id: trailing-whitespace
        name: Trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        description: Prevent giant files from being committed
        entry: check-added-large-files
        language: python
        args: ["--maxkb=1024"]

  - repo: local
    hooks:
      - id: ruff-python
        name: ruff-change-exclude-docs
        description: Check python doc style.
        entry: ruff check 
        language: system
        files: \.(py)$
        types: [file, python]
        args: [--fix, --config=pyproject.toml]

  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout notebook output
        description: trip out notebook 
        entry: nbstripout
        language: system
        exclude: (?x)(^3rdparty/)
        files: \.(ipynb)$
        types: [file]

  - repo: local
    hooks:
      - id: pyright
        name: pyright type check
        description: pyright type check
        entry: pyright
        language: system
        files: \.(py)$
        types: [python]
